In [1]:
import pandas as pd

In [2]:
data = pd.read_excel('Pl_Data.xlsx')

In [3]:
data.head()

,id,name,now_cost,position,team,clean_sheets_per_90,threat_rank_type,expected_assists_per_90,expected_assists,points_per_game_rank,...,threat_rank,ep_this,transfers_in,bps,goals_conceded_per_90,selected_by_percent,influence_rank_type,points_per_game_rank_type,clean_sheets,now_cost_rank
0,3,Granit Xhaka,48,MID,Arsenal,0.39,38,0.12,3.89,47,...,62,7.3,942505,634,1.05,2.7,23,23,13,265
1,4,Mohamed Elneny,41,MID,Arsenal,0.00,233,0.03,0.04,457,...,593,0.0,202760,27,1.62,0.6,226,201,0,634
2,5,Rob Holding,42,DEF,Arsenal,0.00,118,0.02,0.15,405,...,341,0.7,23338,120,2.08,0.2,137,144,0,598
3,6,Thomas Partey,47,MID,Arsenal,0.40,90,0.08,2.17,210,...,152,1.9,110171,468,1.02,0.4,47,80,11,311
4,7,Martin Ã˜degaard,69,MID,Arsenal,0.37,8,0.23,8.02,7,...,18,6.9,7014051,813,1.09,33.3,3,3,13,44

In [4]:
data.shape

(778, 75)

In [5]:
data

,id,name,now_cost,position,team,clean_sheets_per_90,threat_rank_type,expected_assists_per_90,expected_assists,points_per_game_rank,...,threat_rank,ep_this,transfers_in,bps,goals_conceded_per_90,selected_by_percent,influence_rank_type,points_per_game_rank_type,clean_sheets,now_cost_rank
0,3,Granit Xhaka,48,MID,Arsenal,0.39,38,0.12,3.89,47,...,62,7.3,942505,634,1.05,2.7,23,23,13,265
1,4,Mohamed Elneny,41,MID,Arsenal,0.00,233,0.03,0.04,457,...,593,0.0,202760,27,1.62,0.6,226,201,0,634
2,5,Rob Holding,42,DEF,Arsenal,0.00,118,0.02,0.15,405,...,341,0.7,23338,120,2.08,0.2,137,144,0,598
3,6,Thomas Partey,47,MID,Arsenal,0.40,90,0.08,2.17,210,...,152,1.9,110171,468,1.02,0.4,47,80,11,311
4,7,Martin Ã˜degaard,69,MID,Arsenal,0.37,8,0.23,8.02,7,...,18,6.9,7014051,813,1.09,33.3,3,3,13,44
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
773,682,Matheus Santos Carneiro Da Cunha,53,FWD,Wolves,0.47,46,0.02,0.17,265,...,169,0.7,78699,122,1.12,0.1,40,36,5,153
774,698,Mario Lemina,45,MID,Wolves,0.35,188,0.03,0.46,355,...,385,1.5,4325,196,1.94,0.0,125,146,5,359
775,704,Pablo Sarabia,49,MID,Wolves,0.35,122,0.10,0.89,293,...,209,0.3,50058,57,1.06,0.1,164,116,3,225
776,717,Daniel Bentley,40,GKP,Wolves,0.00,32,0.00,0.00,150,...,521,1.0,6232,45,1.50,0.0,32,25,0,651
777,721,JoÃ£o Victor Gomes da Silva,45,MID,Wolves,0.28,179,0.02,0.11,337,...,366,0.5,10923,84,2.50,0.0,144,135,2,395

In [9]:
arsenal_data = data[data['team'] == 'Arsenal']
Liverpool_data = data[data['team'] == 'Liverpool']
Mancity_data = data[data['team'] == 'Manchester city']
Manutd_data = data[data['team'] == 'Manchester united']
chelsea_data = data[data['team'] == 'Chelsea']
tottenham_data = data[data['team'] == 'Tottenham']

In [10]:
Liverpool_data.head()

,id,name,now_cost,position,team,clean_sheets_per_90,threat_rank_type,expected_assists_per_90,expected_assists,points_per_game_rank,...,threat_rank,ep_this,transfers_in,bps,goals_conceded_per_90,selected_by_percent,influence_rank_type,points_per_game_rank_type,clean_sheets,now_cost_rank
436,274,James Milner,44,MID,Liverpool,0.30,147,0.17,1.63,428,...,283,2.0,156314,187,1.21,0.6,132,187,3,470
437,275,Jordan Henderson,53,MID,Liverpool,0.35,116,0.16,3.59,331,...,196,2.8,69647,401,1.31,0.5,93,132,8,133
438,276,Joel Matip,59,DEF,Liverpool,0.25,87,0.08,0.93,216,...,289,1.0,136871,216,1.65,0.9,113,77,3,72
439,277,Thiago AlcÃ¡ntara do Nascimento,51,MID,Liverpool,0.14,149,0.08,1.18,382,...,293,0.0,113597,194,1.65,0.6,113,163,2,168
440,278,Alex Oxlade-Chamberlain,49,MID,Liverpool,0.00,151,0.05,0.18,276,...,296,1.0,4977,57,1.90,0.0,176,105,0,223