In [1]:
import pandas as pd

In [2]:
data = pd.read_excel('Pl_Data.xlsx')

In [3]:
data.head()

,id,name,now_cost,position,team,clean_sheets_per_90,threat_rank_type,expected_assists_per_90,expected_assists,points_per_game_rank,...,threat_rank,ep_this,transfers_in,bps,goals_conceded_per_90,selected_by_percent,influence_rank_type,points_per_game_rank_type,clean_sheets,now_cost_rank
0,3,Granit Xhaka,48,MID,Arsenal,0.39,38,0.12,3.89,47,...,62,7.3,942505,634,1.05,2.7,23,23,13,265
1,4,Mohamed Elneny,41,MID,Arsenal,0.00,233,0.03,0.04,457,...,593,0.0,202760,27,1.62,0.6,226,201,0,634
2,5,Rob Holding,42,DEF,Arsenal,0.00,118,0.02,0.15,405,...,341,0.7,23338,120,2.08,0.2,137,144,0,598
3,6,Thomas Partey,47,MID,Arsenal,0.40,90,0.08,2.17,210,...,152,1.9,110171,468,1.02,0.4,47,80,11,311
4,7,Martin Ã˜degaard,69,MID,Arsenal,0.37,8,0.23,8.02,7,...,18,6.9,7014051,813,1.09,33.3,3,3,13,44

In [4]:
data.shape

(778, 75)